#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
  #name: server-image-pv-claim
  #labels:
    #app: imagehost
#spec:
  #accessModes:
    #- ReadWriteOnce
  #resources:
    #requests:
      #storage: 100Gi
#---
apiVersion: v1
kind: Service
metadata:
  name: imagehost
  labels:
    app: imagehost
spec:
  type: NodePort
  ports:
    - port: 3000
  selector:
    app: imagehost
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: imagehost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imagehost
  template:
    metadata:
      labels:
        app: imagehost

    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - server
      containers:
      - name: imagehost
        image: ghcr.io/john2143/john2143.com:20
        imagePullPolicy: Always

        ports:
        - containerPort: 3000

        volumeMounts:
        - mountPath: /app/juushFiles
          name: data-volume

        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 512Mi

      tolerations:
      - key: "server"
        operator: "Exists"
        effect: "PreferNoSchedule"

      volumes:
      - name: data-volume
        hostPath:
          path: /data/john/juushFiles
          type: Directory
        #emptyDir:
          #sizeLimit: 100Mi
        #persistentVolumeClaim:
          #claimName: server-image-pv-claim
