apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-volume-claim
  labels:
    app: mongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  type: NodePort
  ports:
    - port: 27017
      nodePort: 32052
  selector:
    app: mongo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
      backing: fargate
  template:
    metadata:
      labels:
        app: mongo
        backing: fargate

    spec:
      containers:
      - name: mongo
        image: mongo
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 27017

        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: pass

        volumeMounts:
          - mountPath: /data/db
            name: mongodata

      volumes:
      - name: mongodata
        #emptyDir:
          #sizeLimit: 500Mi
        persistentVolumeClaim:
          claimName: mongo-volume-claim

