apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etc-dnsmasq-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etc-pihole-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns
  labels:
    app: pihole
spec:
  type: NodePort
  ports:
    - port: 53
      protocol: UDP
      name: dnsudp
      nodePort: 30053
    - port: 53
      protocol: TCP
      name: dnstcp
      nodePort: 30053
  selector:
    app: pihole
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-http
  labels:
    app: pihole
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30081
  selector:
    app: pihole
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-67
  labels:
    app: pihole
spec:
  type: NodePort
  ports:
    - port: 67
      nodePort: 30067
  selector:
    app: pihole
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole

    spec:
      #tolerations:
      #- key: "office"
        #operator: "Exists"
        #effect: "NoExecute"
      # hostNetwork: true
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 127.0.0.1
        searches:
          - cluster.local
          - default.svc.cluster.local
          - svc.cluster.local
          - john2143.com
        options:
          - name: ndots
            value: "5"
          - name: edns0


      containers:
      - name: pihole
        image: pihole/pihole@sha256:8b1f31f46d94c3c1b8f509b302f28b4028483009bd27a9cbfd9b80185dd0687d
        imagePullPolicy: Always

        ports:
        - containerPort: 53
        - containerPort: 53
          protocol: UDP
        - containerPort: 67
        - containerPort: 80

        env:
        - name: TZ
          value: "America/New_York"
        - name: WEBPASSWORD
          value: "password1"

        volumeMounts:
        - mountPath: /etc/pihole
          name: etc-pihole
        - mountPath: /etc/dnsmasq.d
          name: etc-dnsmasq

        resources:
          requests:
            cpu: 200m
            memory: 1G
          limits:
            cpu: 500m
            memory: 2G

      volumes:
      - name: etc-pihole
        persistentVolumeClaim:
          claimName: etc-pihole-volume-claim
      - name: etc-dnsmasq
        persistentVolumeClaim:
          claimName: etc-dnsmasq-volume-claim

