apiVersion: v1
kind: PersistentVolume
metadata:
  name: closet-pv
spec:
  capacity:
    storage: 150Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  # persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /mnt/kubepv/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - closet
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: server-pv
spec:
  capacity:
    storage: 300Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  # persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /data/john/kube/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - server
