apiVersion: v1
kind: PersistentVolume
metadata:
  name: downstairs-pv
spec:
  capacity:
    storage: 150Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  # persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /mnt/kubepv/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - downstairs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: server-image-pv
spec:
  capacity:
    storage: 1000Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  # persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /data/john/juushFiles/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - server

